# Generated by Django 5.1.2 on 2024-11-08 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='categoria',
            new_name='categoria_id',
        ),
        migrations.RenameField(
            model_name='receita',
            old_name='subcategoria',
            new_name='subcategoria_id',
        ),
    ]
