# Generated by Django 5.1.2 on 2024-11-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_receitas', '0002_rename_categoria_receita_categoria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
