# Generated by Django 5.1.2 on 2024-11-16 03:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo_receitas', '0003_alter_categoria_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('receita', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategoria',
            unique_together={('nome', 'categoria')},
        ),
    ]
